name: Run unittests on push

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.3"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run unittests
        run: uv run python3 -m unittest discover tests